"use client";

import { useEffect, useState } from "react";

type Settings={id:string;enabled:boolean;cadence:"hourly"|"daily";cadence_label:string;interval_minutes:number;daily_time:string|null;timezone_name:string;analysis_delay_minutes:number;scheduled_task_enabled:boolean;manual_command:string;next_extraction_at:string|null;last_extraction_requested_at:string|null;last_schedule_sync_at:string|null;updated_by_username:string};
type Collection<T>=T[]|{results?:T[]};
const API=process.env.NEXT_PUBLIC_API_URL||"/api/v1";const ENDPOINT=`${API}/procurement/automation-settings/`;
const field={width:"100%",boxSizing:"border-box",padding:9,border:"1px solid #cbd5e1",borderRadius:9,font:"inherit"} as const;
function date(value:string|null){if(!value)return"ثبت نشده";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"medium",timeStyle:"short"}).format(d);}
async function csrf(){const r=await fetch(`${API}/auth/session/`,{credentials:"include",headers:{Accept:"application/json"}});if(!r.ok)throw new Error("نشست کاربری در دسترس نیست.");return String(((await r.json())as{csrf_token?:string}).csrf_token||"");}
async function getSettings(){const r=await fetch(ENDPOINT,{credentials:"include",headers:{Accept:"application/json"}});if(!r.ok)throw new Error("دریافت تنظیمات خودکارسازی انجام نشد.");const p=await r.json() as Collection<Settings>;const items=Array.isArray(p)?p:(p.results||[]);if(!items[0])throw new Error("تنظیمات خودکارسازی هنوز ایجاد نشده است.");return items[0];}
export default function AutomationControlPanel({onClose}:{onClose:()=>void}){
 const [data,setData]=useState<Settings|null>(null),[enabled,setEnabled]=useState(false),[cadence,setCadence]=useState<"hourly"|"daily">("daily"),[interval,setInterval]=useState(60),[dailyTime,setDailyTime]=useState("07:00"),[delay,setDelay]=useState(15),[working,setWorking]=useState(false),[message,setMessage]=useState("");
 function apply(item:Settings){setData(item);setEnabled(item.enabled);setCadence(item.cadence);setInterval(item.interval_minutes);setDailyTime((item.daily_time||"07:00").slice(0,5));setDelay(item.analysis_delay_minutes);}
 useEffect(()=>{getSettings().then(apply).catch(e=>setMessage(e instanceof Error?e.message:"دریافت تنظیمات انجام نشد."));},[]);
 async function save(){if(!data)return;setWorking(true);setMessage("");try{const token=await csrf();const r=await fetch(`${ENDPOINT}${data.id}/`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRFToken":token,Accept:"application/json"},body:JSON.stringify({enabled,cadence,interval_minutes:Math.max(60,interval),daily_time:cadence==="daily"?dailyTime:null,timezone_name:"Asia/Tehran",analysis_delay_minutes:Math.max(0,delay),scheduled_task_enabled:true})});const p=await r.json() as Settings&{detail?:string};if(!r.ok)throw new Error(p.detail||"ذخیره تنظیمات انجام نشد.");apply(p);setMessage("تنظیمات زمان‌بندی ذخیره شد؛ تحلیل‌ها فقط به‌صورت Draft و نیازمند بازبینی انسانی خواهند بود.");}catch(e){setMessage(e instanceof Error?e.message:"ذخیره تنظیمات انجام نشد.");}finally{setWorking(false);}}
 return <div dir="rtl" role="dialog" aria-modal="true" aria-label="کنترل استخراج و تحلیل زمان‌بندی‌شده" style={{position:"fixed",inset:0,zIndex:1600,background:"rgba(15,23,42,.64)",display:"grid",placeItems:"center",padding:16}}><section style={{width:"min(760px,95vw)",maxHeight:"92vh",overflow:"auto",background:"white",borderRadius:18,padding:18}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid #e2e8f0",paddingBottom:12,marginBottom:14}}><div><small>استخراج افزایشی و تحلیل Draft-only</small><h2 style={{margin:3}}>خودکارسازی مناقصات و تحلیل AI</h2></div><button onClick={onClose} aria-label="بستن" style={{border:0,fontSize:24}}>×</button></header>{message&&<div role="status" style={{padding:9,borderRadius:9,background:message.includes("انجام نشد")||message.includes("هنوز")?"#fff1f2":"#ecfdf5",marginBottom:12}}>{message}</div>}{!data?<p>در حال دریافت تنظیمات...</p>:<div style={{display:"grid",gap:12}}><div style={{padding:10,border:"1px solid #fed7aa",background:"#fff7ed",borderRadius:9,color:"#9a3412"}}>سیستم فقط رکوردهای جدید یا تغییرکرده را وارد صف تحلیل می‌کند. خروجی AI منتشر یا انتخاب نمی‌شود و همیشه در مرکز بازبینی باقی می‌ماند.</div><label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> فعال‌بودن استخراج و تحلیل زمان‌بندی‌شده</label><label>تناوب<select value={cadence} onChange={e=>setCadence(e.target.value as "hourly"|"daily")} style={field}><option value="daily">روزانه</option><option value="hourly">ساعتی</option></select></label>{cadence==="daily"?<label>ساعت اجرای روزانه<input type="time" value={dailyTime} onChange={e=>setDailyTime(e.target.value)} style={field}/></label>:<label>فاصله اجرا به دقیقه<input type="number" min={60} max={10080} value={interval} onChange={e=>setInterval(Number(e.target.value))} style={field}/></label>}<label>تأخیر ایجاد درخواست تحلیل پس از استخراج، دقیقه<input type="number" min={0} max={1440} value={delay} onChange={e=>setDelay(Number(e.target.value))} style={field}/></label><dl style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,margin:0}}><div><dt>اجرای بعدی</dt><dd style={{margin:0,fontWeight:700}}>{date(data.next_extraction_at)}</dd></div><div><dt>آخرین درخواست استخراج</dt><dd style={{margin:0,fontWeight:700}}>{date(data.last_extraction_requested_at)}</dd></div><div><dt>منطقه زمانی</dt><dd style={{margin:0}}>{data.timezone_name}</dd></div><div><dt>فرمان تحلیل</dt><dd style={{margin:0}}>{data.manual_command}</dd></div></dl><button disabled={working} onClick={()=>void save()} style={{padding:11,border:0,borderRadius:9,background:"#0f766e",color:"white",fontWeight:700}}>{working?"در حال ذخیره...":"ذخیره تنظیمات خودکارسازی"}</button></div>}</section></div>;
}
