"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import styles from "./workspace-v4.module.css";

type Tab = "dashboard" | "tenders" | "inquiries" | "direct" | "management";
type WorkflowView = "all" | "recommended" | "selected" | "submitted" | "results";
type DirectStage = "new" | "reviewing" | "selected" | "preparing" | "submitted" | "won" | "lost";
type NoticeStage = "" | "selected" | "preparing" | "submitted" | "results";
type Notice = { id:string; referenceCode:string|null; kind:"tender"|"inquiry"; title:string; employer:string; province:string; source:string; deadline:string|null; recommended:boolean; stage:NoticeStage; result:string; score:number|null; responsible:string; nextAction:string; progress:number; documents:string[] };
type DirectReferral = { id:string; referenceCode:string|null; title:string; employer:string; opportunityType:string; domain:string; province:string; city:string; description:string; estimatedValue:string; probability:number|null; responsible:string; targetDeadline:string|null; contactName:string; contactPhone:string; contactEmail:string; confidentiality:string; stage:DirectStage; documents:string[] };

const fa = new Intl.NumberFormat("fa-IR");
const tabs:[Tab,string][] = [["dashboard","داشبورد مدیریتی"],["tenders","مناقصات"],["inquiries","استعلامات"],["direct","ارجاعات مستقیم"],["management","مدیریت زیرسامانه"]];
const views:[WorkflowView,string][] = [["all","همه"],["recommended","پیشنهادی"],["selected","منتخب"],["submitted","ارسال‌شده"],["results","نتایج"]];

const initialNotices:Notice[] = [
 {id:"T1",referenceCode:"TND-10000",kind:"tender",title:"خدمات مشاوره طراحی و نظارت مجموعه اداری",employer:"شرکت توسعه عمران",province:"تهران",source:"هزاره",deadline:"2026-07-25T16:00:00+03:30",recommended:true,stage:"selected",result:"",score:91,responsible:"محمد ملکی",nextAction:"تقسیم کار تهیه پیشنهاد",progress:35,documents:["شرح خدمات.pdf"]},
 {id:"T2",referenceCode:"TND-10001",kind:"tender",title:"مطالعات طرح جامع و برنامه‌ریزی فضایی",employer:"اداره کل راه و شهرسازی",province:"فارس",source:"پارس نماد داده",deadline:"2026-07-30T14:00:00+03:30",recommended:true,stage:"preparing",result:"",score:95,responsible:"کارشناس مناقصات",nextAction:"تهیه ساختار شکست خدمات",progress:62,documents:["رزومه تیم.pdf","روش انجام کار.docx"]},
 {id:"T3",referenceCode:null,kind:"tender",title:"طراحی تأسیسات بیمارستان",employer:"دانشگاه علوم پزشکی",province:"البرز",source:"هزاره",deadline:"2026-07-27T12:00:00+03:30",recommended:false,stage:"",result:"",score:null,responsible:"",nextAction:"بررسی اولیه",progress:0,documents:[]},
 {id:"T4",referenceCode:null,kind:"tender",title:"مطالعات بازآفرینی بافت شهری",employer:"شهرداری نمونه",province:"کرمان",source:"هزاره",deadline:"2026-08-02T15:00:00+03:30",recommended:true,stage:"",result:"",score:87,responsible:"",nextAction:"تصمیم مدیر",progress:0,documents:[]},
 {id:"T5",referenceCode:"TND-10002",kind:"tender",title:"مطالعات امکان‌سنجی شهرک صنعتی",employer:"شرکت شهرک‌های صنعتی",province:"آذربایجان شرقی",source:"پارس نماد داده",deadline:"2026-07-22T15:00:00+03:30",recommended:true,stage:"submitted",result:"",score:82,responsible:"توسعه کسب‌وکار",nextAction:"پیگیری نتیجه",progress:100,documents:["پیشنهاد فنی.pdf","رسید ارسال.pdf"]},
 {id:"I1",referenceCode:"INQ-10000",kind:"inquiry",title:"استعلام خدمات نقشه‌برداری",employer:"شهرداری منطقه",province:"تهران",source:"پارس نماد داده",deadline:"2026-07-23T13:00:00+03:30",recommended:true,stage:"selected",result:"",score:88,responsible:"کارشناس مناقصات",nextAction:"دریافت قیمت و تأیید مدیر",progress:70,documents:[]},
 {id:"I2",referenceCode:"INQ-10001",kind:"inquiry",title:"استعلام گزارش توجیهی و امکان‌سنجی",employer:"منطقه ویژه اقتصادی",province:"بوشهر",source:"هزاره",deadline:"2026-07-26T15:00:00+03:30",recommended:true,stage:"preparing",result:"",score:86,responsible:"واحد مطالعات",nextAction:"جلسه با کارشناس مالی",progress:48,documents:["پیش‌نویس پیشنهاد.pdf"]},
 {id:"I3",referenceCode:null,kind:"inquiry",title:"استعلام طراحی روشنایی محوطه صنعتی",employer:"شرکت تولیدی نمونه",province:"قزوین",source:"پارس نماد داده",deadline:"2026-07-24T10:00:00+03:30",recommended:false,stage:"",result:"",score:null,responsible:"",nextAction:"دریافت پیوست فنی",progress:0,documents:[]},
 {id:"I4",referenceCode:null,kind:"inquiry",title:"استعلام مطالعات ترافیکی",employer:"سازمان حمل‌ونقل",province:"تهران",source:"هزاره",deadline:"2026-07-29T12:00:00+03:30",recommended:true,stage:"",result:"",score:84,responsible:"",nextAction:"تصمیم مدیر",progress:0,documents:[]},
];
const initialDirect:DirectReferral[] = [
 {id:"D1",referenceCode:null,title:"رایزنی طرح توسعه پردیس اداری",employer:"گروه سرمایه‌گذاری پارس",opportunityType:"رایزنی با کارفرما",domain:"معماری اداری",province:"تهران",city:"تهران",description:"طراحی و توسعه پردیس اداری",estimatedValue:"",probability:40,responsible:"محمد ملکی",targetDeadline:null,contactName:"نماینده کارفرما",contactPhone:"",contactEmail:"",confidentiality:"داخلی",stage:"new",documents:[]},
 {id:"D2",referenceCode:null,title:"مطالعات امکان‌سنجی نیروگاه خورشیدی",employer:"شرکت انرژی نو",opportunityType:"معرفی مستقیم",domain:"امکان‌سنجی",province:"یزد",city:"",description:"مطالعات فنی و اقتصادی",estimatedValue:"",probability:55,responsible:"توسعه کسب‌وکار",targetDeadline:"2026-08-10T12:00:00+03:30",contactName:"",contactPhone:"",contactEmail:"",confidentiality:"داخلی",stage:"reviewing",documents:[]},
 {id:"D3",referenceCode:"DIR-10000",title:"دعوت محدود طراحی مجموعه درمانی",employer:"بنیاد توسعه سلامت",opportunityType:"دعوت محدود",domain:"معماری درمانی",province:"تهران",city:"",description:"طراحی معماری و تأسیسات",estimatedValue:"78000000000",probability:80,responsible:"مدیر فنی",targetDeadline:"2026-07-22T12:00:00+03:30",contactName:"دبیرخانه بنیاد",contactPhone:"",contactEmail:"",confidentiality:"داخلی",stage:"submitted",documents:["پیشنهاد معماری.pdf","رسید ایمیل.pdf"]},
];

function urgency(value:string|null){ if(!value)return{tone:"unknown",label:"تاریخ نامشخص",remaining:"نامشخص"}; const hours=Math.ceil((new Date(value).getTime()-Date.now())/3600000); if(hours<0)return{tone:"critical",label:"مهلت گذشته",remaining:`${fa.format(Math.abs(hours))} ساعت گذشته`}; if(hours<24)return{tone:"critical",label:"فوریت بحرانی",remaining:`${fa.format(hours)} ساعت باقی‌مانده`}; if(hours<=72)return{tone:"high",label:"فوریت زیاد",remaining:`${fa.format(Math.ceil(hours/24))} روز باقی‌مانده`}; return{tone:"normal",label:"عادی",remaining:`${fa.format(Math.ceil(hours/24))} روز باقی‌مانده`}; }
function noticeMatches(n:Notice,v:WorkflowView){ if(v==="all")return true; if(v==="recommended")return n.recommended&&!n.stage; if(v==="selected")return n.stage==="selected"||n.stage==="preparing"; if(v==="submitted")return n.stage==="submitted"; return n.stage==="results"; }
function directMatches(d:DirectReferral,v:WorkflowView){ if(v==="all")return true; if(v==="recommended")return d.stage==="reviewing"; if(v==="selected")return d.stage==="selected"||d.stage==="preparing"; if(v==="submitted")return d.stage==="submitted"; return d.stage==="won"||d.stage==="lost"; }
function nextCode(items:{referenceCode:string|null}[],prefix:string){ const max=Math.max(9999,...items.map(x=>x.referenceCode).filter((x):x is string=>Boolean(x&&x.startsWith(prefix+"-"))).map(x=>Number(x.split("-")[1])||9999)); return `${prefix}-${max+1}`; }

export default function ProcurementWorkspaceV7(){
 const [tab,setTab]=useState<Tab>("dashboard"); const [noticeView,setNoticeView]=useState<WorkflowView>("all"); const [directView,setDirectView]=useState<WorkflowView>("all"); const [notices,setNotices]=useState(initialNotices); const [direct,setDirect]=useState(initialDirect); const [search,setSearch]=useState(""); const [message,setMessage]=useState(""); const [showDirectModal,setShowDirectModal]=useState(false); const [selected,setSelected]=useState<{title:string;code:string|null;employer:string;status:string;documents:string[]}|null>(null); const [schedule,setSchedule]=useState({cadence:"daily",dailyTime:"17:00",intervalHours:5});
 const filteredNotices=useMemo(()=>notices.filter(n=>(tab==="tenders"?n.kind==="tender":n.kind==="inquiry")&&noticeMatches(n,noticeView)&&(!search||`${n.referenceCode||""} ${n.title} ${n.employer}`.includes(search))),[notices,tab,noticeView,search]);
 const filteredDirect=useMemo(()=>direct.filter(d=>directMatches(d,directView)&&(!search||`${d.referenceCode||""} ${d.title} ${d.employer}`.includes(search))),[direct,directView,search]);
 function notify(text:string){setMessage(text);window.setTimeout(()=>setMessage(""),3200)}
 function updateNotice(id:string,change:Partial<Notice>){setNotices(xs=>xs.map(x=>x.id===id?{...x,...change}:x))}
 function updateDirect(id:string,change:Partial<DirectReferral>){setDirect(xs=>xs.map(x=>x.id===id?{...x,...change}:x))}
 function selectNotice(id:string){setNotices(xs=>{const item=xs.find(x=>x.id===id);if(!item)return xs;const prefix=item.kind==="tender"?"TND":"INQ";const code=item.referenceCode||nextCode(xs.filter(x=>x.kind===item.kind),prefix);notify(`پرونده منتخب شد و کد ${code} دریافت کرد.`);return xs.map(x=>x.id===id?{...x,stage:"selected",referenceCode:code}:x)})}
 function selectDirect(id:string){setDirect(xs=>{const item=xs.find(x=>x.id===id);if(!item)return xs;const code=item.referenceCode||nextCode(xs,"DIR");notify(`ارجاع منتخب شد و کد ${code} دریافت کرد.`);return xs.map(x=>x.id===id?{...x,stage:"selected",referenceCode:code}:x)})}
 function uploadNotice(id:string,e:ChangeEvent<HTMLInputElement>){const names=Array.from(e.target.files||[]).map(f=>f.name);setNotices(xs=>xs.map(x=>x.id===id?{...x,documents:[...x.documents,...names]}:x));notify(`${fa.format(names.length)} سند به پرونده افزوده شد.`)}
 function uploadDirect(id:string,e:ChangeEvent<HTMLInputElement>){const names=Array.from(e.target.files||[]).map(f=>f.name);setDirect(xs=>xs.map(x=>x.id===id?{...x,documents:[...x.documents,...names]}:x));notify(`${fa.format(names.length)} سند به پرونده افزوده شد.`)}
 function registerDirect(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const values=Object.fromEntries(form.entries());if(!Object.values(values).some(v=>String(v).trim())){notify("حداقل یک اطلاعات معنادار وارد کنید.");return}const item:DirectReferral={id:`D-${Date.now()}`,referenceCode:null,title:String(form.get("title")||"").trim(),employer:String(form.get("employer")||"").trim(),opportunityType:String(form.get("opportunityType")||"نیازمند تعیین"),domain:String(form.get("domain")||"").trim(),province:String(form.get("province")||"").trim(),city:String(form.get("city")||"").trim(),description:String(form.get("description")||"").trim(),estimatedValue:String(form.get("estimatedValue")||"").trim(),probability:form.get("probability")?Number(form.get("probability")):null,responsible:String(form.get("responsible")||"").trim(),targetDeadline:String(form.get("targetDeadline")||"")||null,contactName:String(form.get("contactName")||"").trim(),contactPhone:String(form.get("contactPhone")||"").trim(),contactEmail:String(form.get("contactEmail")||"").trim(),confidentiality:String(form.get("confidentiality")||"داخلی"),stage:"new",documents:[]};setDirect(xs=>[item,...xs]);e.currentTarget.reset();setDirectView("all");setShowDirectModal(false);notify("ارجاع در «همه» ثبت شد؛ کد دائمی پس از انتخاب ساخته می‌شود.")}
 function noticeActions(n:Notice){if(noticeView==="all")return <>{!n.recommended&&!n.stage&&<button className={styles.primaryButton} onClick={()=>updateNotice(n.id,{recommended:true})}>افزودن به پیشنهادی</button>}<button className={styles.secondaryButton} onClick={()=>setSelected({title:n.title,code:n.referenceCode,employer:n.employer,status:n.stage||"همه",documents:n.documents})}>مشاهده</button></>;if(noticeView==="recommended")return <><button className={styles.primaryButton} onClick={()=>selectNotice(n.id)}>انتخاب و ساخت کد</button><button className={styles.dangerButton} onClick={()=>updateNotice(n.id,{recommended:false})}>حذف</button></>;if(noticeView==="selected")return <><label className={styles.fileButton}>بارگذاری اسناد<input type="file" multiple onChange={e=>uploadNotice(n.id,e)}/></label><button className={styles.primaryButton} onClick={()=>updateNotice(n.id,{stage:"submitted",progress:100})}>ارسال شد</button><button className={styles.dangerButton} onClick={()=>updateNotice(n.id,{stage:"",recommended:true})}>حذف</button></>;if(noticeView==="submitted")return <><button className={styles.primaryButton} onClick={()=>updateNotice(n.id,{stage:"results",result:"برنده"})}>ثبت نتیجه</button><button className={styles.secondaryButton} onClick={()=>setSelected({title:n.title,code:n.referenceCode,employer:n.employer,status:"ارسال‌شده",documents:n.documents})}>اسناد</button></>;return <button className={styles.secondaryButton} onClick={()=>setSelected({title:n.title,code:n.referenceCode,employer:n.employer,status:n.result||"نتایج",documents:n.documents})}>مشاهده پرونده</button>}
 function directActions(d:DirectReferral){if(directView==="all")return <>{d.stage==="new"?<button className={styles.primaryButton} onClick={()=>updateDirect(d.id,{stage:"reviewing"})}>افزودن به پیشنهادی</button>:<button className={styles.statusButton} disabled>{d.stage==="reviewing"?"پیشنهادی":d.stage==="selected"?"منتخب":d.stage==="submitted"?"ارسال‌شده":"نتیجه"}</button>}<button className={styles.secondaryButton} onClick={()=>setSelected({title:d.title||"ارجاع بدون عنوان",code:d.referenceCode,employer:d.employer||"کارفرما ثبت نشده",status:d.stage,documents:d.documents})}>مشاهده</button></>;if(directView==="recommended")return <><button className={styles.primaryButton} onClick={()=>selectDirect(d.id)}>انتخاب و ساخت کد</button><button className={styles.dangerButton} onClick={()=>updateDirect(d.id,{stage:"new"})}>حذف</button></>;if(directView==="selected")return <><label className={styles.fileButton}>بارگذاری اسناد<input type="file" multiple onChange={e=>uploadDirect(d.id,e)}/></label><button className={styles.primaryButton} onClick={()=>updateDirect(d.id,{stage:"submitted"})}>ارسال شد</button><button className={styles.dangerButton} onClick={()=>updateDirect(d.id,{stage:"reviewing"})}>حذف</button></>;if(directView==="submitted")return <><button className={styles.primaryButton} onClick={()=>updateDirect(d.id,{stage:"won"})}>ثبت موفق</button><button className={styles.secondaryButton} onClick={()=>setSelected({title:d.title,code:d.referenceCode,employer:d.employer,status:"ارسال‌شده",documents:d.documents})}>اسناد</button></>;return <button className={styles.secondaryButton} onClick={()=>setSelected({title:d.title,code:d.referenceCode,employer:d.employer,status:d.stage==="won"?"موفق":"ناموفق",documents:d.documents})}>مشاهده پرونده</button>}
 const codePart=(code:string|null)=><>{code&&<> · <span className={styles.codeBadge}>{code}</span></>}</>;
 return <main className={styles.page} dir="rtl">
  <header className={styles.header}><div><span>زیرسامانه تخصصی PDP One</span><h1>مناقصات و استعلامات</h1><p>شماره ردیف برای نمایش فهرست است؛ کد دائمی فقط هنگام ورود به منتخب ساخته می‌شود.</p></div><Link href="/">بازگشت به سامانه</Link></header>
  <div className={styles.banner}><b>Preview تعاملی</b><span>همه و پیشنهادی بدون کد دائمی؛ منتخب و مراحل بعد دارای کد TND / INQ / DIR هستند.</span></div>
  <nav className={styles.tabs}>{tabs.map(([id,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>{setTab(id);setSearch("");setNoticeView("all");setDirectView("all")}}>{label}</button>)}</nav>{message&&<div className={styles.message}>{message}</div>}
  {tab==="dashboard"&&<section><div className={styles.kpis}><article className={styles.kpi}><span>فراخوان امروز</span><b>۴</b><small>۲ مناقصه · ۲ استعلام</small></article><article className={styles.kpi}><span>پیشنهادی امروز</span><b>۲</b><small>بدون کد تا زمان انتخاب</small></article><article className={styles.kpi}><span>فراخوان دیروز</span><b>۳</b><small>۲ مناقصه · ۱ استعلام</small></article><article className={styles.kpi}><span>پیشنهادی دیروز</span><b>۳</b><small>نیازمند تصمیم</small></article></div><div className={styles.dashboardGrid}><article className={styles.panel}><h2>هشدارهای مدیریتی</h2><div className={styles.alertList}><span>۳ اقدام عقب‌افتاده</span><span>۲ پرونده بدون مسئول</span><span>۴ پرونده نزدیک مهلت</span></div></article><article className={styles.panel}><h2>بازیابی سریع با کد</h2><p>بازیابی با کد از مرحله منتخب به بعد فعال است؛ مانند <b>TND-10001</b>، <b>INQ-10000</b> یا <b>DIR-10000</b>.</p></article></div></section>}
  {(tab==="tenders"||tab==="inquiries")&&<section><div className={styles.sectionHeading}><div><span>فرآیند تصمیم‌گیری</span><h2>{tab==="tenders"?"مناقصات":"استعلامات"}</h2></div><small>در همه و پیشنهادی فقط ردیف نمایش داده می‌شود؛ کد با ورود به منتخب ایجاد می‌شود.</small></div><div className={styles.views}>{views.map(([id,label])=><button key={id} className={noticeView===id?styles.active:""} onClick={()=>setNoticeView(id)}>{label}</button>)}</div><div className={styles.toolbar}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجو با عنوان، کارفرما یا کد پرونده منتخب..."/><span>{fa.format(filteredNotices.length)} رکورد</span></div><div className={styles.recordList}>{filteredNotices.map((n,index)=>{const u=urgency(n.deadline);return <article className={styles.record} key={n.id}><div><div className={styles.recordTop}><small><b>ردیف {fa.format(index+1)}</b>{codePart(n.referenceCode)} · {n.source}</small><span className={`${styles.urgency} ${styles[u.tone]}`}>{u.label}</span></div><h3>{n.title}</h3><p>{n.employer}</p><div className={styles.facts}><span>{u.remaining}</span><span>اولویت: {n.score??"تحلیل نشده"}</span>{n.documents.length>0&&<span>{fa.format(n.documents.length)} سند</span>}</div></div><div className={styles.decision}><span className={styles.stage}>{n.result||n.stage||(n.recommended?"پیشنهادی":"همه")}</span><dl><div><dt>مسئول</dt><dd>{n.responsible||"تعیین نشده"}</dd></div><div><dt>اقدام بعدی</dt><dd>{n.nextAction}</dd></div></dl><div className={styles.actions}>{noticeActions(n)}</div></div></article>})}</div></section>}
  {tab==="direct"&&<section><div className={styles.sectionHeading}><div><span>فرآیند ارجاعات مستقیم</span><h2>ارجاعات مستقیم</h2></div><button className={styles.primaryButton} onClick={()=>setShowDirectModal(true)}>ثبت ارجاع مستقیم جدید</button></div><div className={styles.views}>{views.map(([id,label])=><button key={id} className={directView===id?styles.active:""} onClick={()=>setDirectView(id)}>{label}</button>)}</div><div className={styles.toolbar}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجو با عنوان، کارفرما یا کد پرونده منتخب..."/><span>{fa.format(filteredDirect.length)} رکورد</span></div><div className={styles.recordList}>{filteredDirect.map((d,index)=>{const u=urgency(d.targetDeadline);const facts=[d.domain,d.province,d.city,d.probability!=null?`احتمال تبدیل: ${fa.format(d.probability)}٪`:"",d.documents.length?`${fa.format(d.documents.length)} سند`:""].filter(Boolean);return <article className={styles.record} key={d.id}><div><div className={styles.recordTop}><small><b>ردیف {fa.format(index+1)}</b>{codePart(d.referenceCode)} · {d.opportunityType}</small><span className={`${styles.urgency} ${styles[u.tone]}`}>{u.label}</span></div><h3>{d.title||"ارجاع بدون عنوان"}</h3>{d.employer&&<p>{d.employer}</p>}<div className={styles.facts}>{facts.map(f=><span key={f}>{f}</span>)}</div></div><div className={styles.decision}><span className={styles.stage}>{d.stage==="new"?"همه":d.stage==="reviewing"?"پیشنهادی":d.stage==="selected"||d.stage==="preparing"?"منتخب":d.stage==="submitted"?"ارسال‌شده":d.stage==="won"?"موفق":"ناموفق"}</span><dl>{d.responsible&&<div><dt>مسئول</dt><dd>{d.responsible}</dd></div>}{d.contactName&&<div><dt>رابط</dt><dd>{d.contactName}</dd></div>}</dl><div className={styles.actions}>{directActions(d)}</div></div></article>})}</div></section>}
  {tab==="management"&&<section><div className={styles.sectionHeading}><div><span>تنظیمات</span><h2>مدیریت زیرسامانه</h2></div></div><div className={styles.managementGrid}><article className={styles.panel}><h2>زمان‌بندی استخراج</h2><div className={styles.scheduleGrid}><label>نوع برنامه<select value={schedule.cadence} onChange={e=>setSchedule({...schedule,cadence:e.target.value})}><option value="daily">روزانه</option><option value="hourly">ساعتی</option></select></label>{schedule.cadence==="daily"?<label>ساعت روزانه<input type="time" value={schedule.dailyTime} onChange={e=>setSchedule({...schedule,dailyTime:e.target.value})}/></label>:<label>هر چند ساعت یک‌بار<input type="number" min="1" max="168" value={schedule.intervalHours} onChange={e=>setSchedule({...schedule,intervalHours:Number(e.target.value)})}/></label>}</div></article><article className={styles.panel}><h2>زمان ساخت کد</h2><p>کد دائمی هنگام انتخاب پرونده ساخته می‌شود، نه هنگام استخراج، ثبت اولیه یا پیشنهادشدن.</p><dl><div><dt>مناقصه منتخب</dt><dd>TND-10000</dd></div><div><dt>استعلام منتخب</dt><dd>INQ-10000</dd></div><div><dt>ارجاع مستقیم منتخب</dt><dd>DIR-10000</dd></div></dl></article></div></section>}
  {showDirectModal&&<div className={styles.backdrop} onMouseDown={()=>setShowDirectModal(false)}><section className={`${styles.modal} ${styles.largeModal}`} onMouseDown={e=>e.stopPropagation()}><header><div><small>ثبت اولیه بدون کد دائمی</small><h2>ثبت ارجاع مستقیم جدید</h2><p>رکورد ابتدا در «همه» قرار می‌گیرد و پس از ورود به منتخب کد DIR دریافت می‌کند.</p></div><button type="button" onClick={()=>setShowDirectModal(false)}>×</button></header><form className={styles.modalForm} onSubmit={registerDirect}><div className={styles.formGrid}><label>عنوان<input name="title"/></label><label>کارفرما<input name="employer"/></label><label>نوع ارجاع<select name="opportunityType"><option>نیازمند تعیین</option><option>مذاکره مستقیم</option><option>دعوت محدود</option><option>رایزنی با کارفرما</option><option>معرفی مستقیم</option><option>ترک تشریفات</option></select></label><label>حوزه تخصصی<input name="domain"/></label><label>استان<input name="province"/></label><label>شهر<input name="city"/></label><label>مهلت یا تاریخ هدف<input type="datetime-local" name="targetDeadline"/></label><label>مبلغ برآوردی ـ ریال<input name="estimatedValue" inputMode="numeric"/></label><label>احتمال تبدیل ـ درصد<input type="number" min="0" max="100" name="probability"/></label><label>مسئول<input name="responsible"/></label><label>محرمانگی<select name="confidentiality"><option>عادی</option><option>داخلی</option><option>محرمانه</option></select></label><label>نام رابط<input name="contactName"/></label><label>تلفن رابط<input name="contactPhone"/></label><label>ایمیل رابط<input type="email" name="contactEmail"/></label><label className={styles.wideField}>شرح و یادداشت<textarea name="description" rows={4}/></label></div><div className={styles.formActions}><button type="button" className={styles.secondaryButton} onClick={()=>setShowDirectModal(false)}>انصراف</button><button className={styles.primaryButton}>ثبت در همه</button></div></form></section></div>}
  {selected&&<div className={styles.backdrop} onMouseDown={()=>setSelected(null)}><section className={styles.modal} onMouseDown={e=>e.stopPropagation()}><header><div><small>{selected.code?`${selected.code} · `:"بدون کد دائمی · "}{selected.status}</small><h2>{selected.title}</h2><p>{selected.employer}</p></div><button onClick={()=>setSelected(null)}>×</button></header><div className={styles.modalBody}><h3>اسناد پرونده</h3>{selected.documents.length?selected.documents.map(x=><p key={x}>• {x}</p>):<p>سندی ثبت نشده است.</p>}</div></section></div>}
 </main>
}
